import { zipSync, strToU8 } from 'fflate';
import type { LogEntry } from '@/types/domain';
import type { Aggregate } from '@/lib/report/aggregate';

export interface Bijlage1Input {
  period: { from: string; to: string };
  logs: readonly LogEntry[];
  agg: Aggregate;
  reportHtml: string;
  summary: string; // HTML from `summaryForLetter`
}

function csvEscape(value: string | number | boolean | undefined | null): string {
  if (value === undefined || value === null) return '';
  const s = String(value);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function intensityBucket1to5(intensity: number): number {
  return Math.max(1, Math.min(5, Math.ceil(intensity / 2)));
}

function buildLogboekCsv(logs: readonly LogEntry[]): string {
  const header =
    'datum,tijd,type,sterkte_1_10,sterkte_1_5,duur_min,locatie,geluid_db,trilling_max_ms2,trilling_avg_ms2,heeft_audio,omschrijving';
  const rows = logs.map((l) => {
    const d = new Date(l.timestamp);
    const datum = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
    const tijd = `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
    return [
      csvEscape(datum),
      csvEscape(tijd),
      csvEscape(l.type),
      csvEscape(l.intensity),
      csvEscape(intensityBucket1to5(l.intensity)),
      csvEscape(l.durationMinutes),
      csvEscape(l.location),
      csvEscape(l.soundDb ?? ''),
      csvEscape(l.vibration?.max ?? ''),
      csvEscape(l.vibration?.avg ?? ''),
      csvEscape(l.audioClip ? 'ja' : 'nee'),
      csvEscape(l.description ?? ''),
    ].join(',');
  });
  return [header, ...rows].join('\n') + '\n';
}

function buildAggregateCsv(agg: Aggregate): string {
  const lines: string[] = ['key,value'];
  lines.push(`count,${agg.count}`);
  lines.push(`days,${agg.days}`);
  lines.push(`totalDuration,${agg.totalDuration}`);
  lines.push(`avgIntensity,${agg.avgIntensity}`);
  lines.push(`byType.trilling,${agg.byType.trilling}`);
  lines.push(`byType.geluid,${agg.byType.geluid}`);
  lines.push(`byType.beide,${agg.byType.beide}`);
  // byDay as `byDay.YYYY-MM-DD` keys
  for (const [day, count] of Object.entries(agg.byDay).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    lines.push(`byDay.${day},${count}`);
  }
  // byHour as `byHour.0`..`byHour.23`
  agg.byHour.forEach((c, i) => {
    lines.push(`byHour.${i},${c}`);
  });
  return lines.join('\n') + '\n';
}

function buildSummaryTxt(html: string): string {
  // Strip HTML tags to a plain-text version of the summary. Cheap regex;
  // the source HTML is generated by us and well-formed.
  return html
    .replace(/<\/?(p|li|ul|ol|strong|em|small|br)[^>]*>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&ndash;|&mdash;/g, '-')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function reportFilename(period: { from: string; to: string }): string {
  return `overlast-rapport-${period.from}.html`;
}

/**
 * Build the four files of `Bijlage 1` and zip them into a single
 * `Uint8Array`. The output is a normal `deflate` zip that any tool
 * (Finder, Explorer, `unzip`) can extract.
 */
export function buildBijlage1Zip(input: Bijlage1Input): Uint8Array {
  const csv = buildLogboekCsv(input.logs);
  const aggCsv = buildAggregateCsv(input.agg);
  const summaryTxt = buildSummaryTxt(input.summary);

  const files: Record<string, Uint8Array> = {
    [reportFilename(input.period)]: strToU8(input.reportHtml),
    'logboek.csv': strToU8(csv),
    'logboek-aggregaat.csv': strToU8(aggCsv),
    'logboek-samenvatting.txt': strToU8(summaryTxt),
  };

  return zipSync(files, { level: 6 });
}
